import React from "react";

const Bottom_Again=(props)=>{
return(
    <>
    <div className="once_more">
    <div className="bottom_again">
        <div className="video_link">
        <iframe className="iframe_vid" src={props.link1}></iframe>
        <div className="information">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore fugiat voluptate expedita recusandae fugit veniam ullam culpa et ea, ratione officia quo voluptatem voluptatibus corrupti voluptatum maxime ipsa! Illo, ea temporibus excepturi tempora mollitia veniam exercitationem dolorem? Nihil repellat amet iusto doloremque ipsa laudantium ex. Doloremque officiis nihil consequatur atque.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum rerum dolores officia nam veritatis aperiam sequi, nemo omnis at, iste architecto aut corporis blanditiis asperiores hic, ex officiis quae magnam tempora porro? Voluptatum, harum ad. Ut voluptate perspiciatis enim aspernatur reprehenderit ducimus consectetur voluptatem dolore rem suscipit mollitia est exercitationem harum dicta, consequatur commodi libero expedita. Voluptatum assumenda quam nam delectus minima recusandae in, nihil placeat debitis. Excepturi nesciunt dicta porro ex placeat blanditiis tempore optio voluptas. Repellendus, maxime! Officiis veritatis repellat eveniet molestias aspernatur minima quia, cupiditate dolor voluptatibus culpa quisquam provident aperiam nobis! Neque ab inventore cupiditate incidunt?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta nam a neque earum? Quibusdam laboriosam alias rerum illo vero quisquam molestias officiis sequi? Expedita nesciunt sint ducimus quod! Eum vitae eius dolor, exercitationem quae inventore. Laboriosam a quaerat vel earum cumque similique deserunt ipsam. Quaerat atque animi quas incidunt sed deserunt, facilis, possimus facere nihil maiores error autem, iusto dolor nisi eaque. Nam aperiam veritatis et sint voluptate qui facilis amet est facere quaerat numquam, quas animi. Magni alias ipsum necessitatibus vel voluptatem consequatur ab cum eligendi? Sit fuga veniam tempore esse? Architecto qui provident autem natus nisi exLorem100
        </div>
        </div>
        <div className="video_link"><iframe className="iframe_vid" src={props.link2}></iframe><div className="information"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt praesentium, tenetur voluptate sit fuga totam ipsam tempore accusamus repellat ea impedit, itaque eos voluptatem maiores facilis maxime aliquid temporibus cupiditate exercitationem distinctio doloremque porro ab nisi ad! Libero hic voluptates deleniti necessitatibus in adipisci quod, modi dolorem, illo, error quas.Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore libero delectus sint. Aliquam ullam voluptatum nobis sapiente at optio cupiditate, doloremque dolorum placeat ipsum! Dignissimos delectus voluptatibus porro! Voluptate, fugit eos! Vero libero nemo quaerat harum dicta consequuntur, pariatur praesentium ex laudantium amet distinctio, consectetur asperiores commodi! Explicabo autem veritatis eveniet aliquam quam laudantium amet voluptatibus velit atque pariatur, necessitatibus doloremque, quasi aperiam? Ullam, facilis culpa. Non ab vel, esse totam recusandae magnam nesciunt praesentium veniam quae, expedita ducimus? Ratione vitae, nisi error ipsa mollitia cumque? Ullam obcaecati fuga ipsa blanditiis. Ipsum, labore modi accusamus facilis laborum esse quia animi.Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores amet commodi harum corporis? Neque omnis mollitia ullam quam earum quod velit ducimus. Dolores veniam optio veritatis magni reprehenderit voluptates, voluptatibus a, rerum quos iure labore? Et pariatur dolores odit, modi, magnam quidem inventore sed, omnis quam quia nesciunt praesentium. Consectetur officiis vel mollitia neque et labore ut, ullam necessitatibus ad itaque iusto alias assumenda delectus facilis nam velit, nostrum aliquid blanditiis perspiciatis reprehenderit odit magnam? Consequuntur placeat dolorem necessitatibus veritatis temporibus debitis corporis ab eligendi impedit! Dolorem maiores pariatur fugiat enim at esse molestias provident voluptatum perferendis, nam, velit eius!</div></div>
        <div className="video_link"><iframe className="iframe_vid" src={props.link3}></iframe><div className="information">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae ullam facere ab. Unde libero, perspiciatis dolore explicabo dicta quod vitae beatae ut eaque laudantium, eveniet enim tempore, reprehenderit iste laborum fugit? Sapiente, consequuntur commodi! Totam rerum voluptate explicabo ab doloremque unde amet, officiis nihil dolorum cupiditate ad voluptatem quod enim?Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi voluptas ipsam excepturi laudantium accusamus, nemo pariatur nulla sapiente nobis maxime, eius eligendi perferendis ab et quaerat. Laboriosam, soluta voluptates quidem quaerat labore nesciunt. Dolorem, accusantium earum? Possimus, at facilis dicta, aut quaerat voluptatem quasi nostrum tempora optio, quisquam adipisci corrupti. Mollitia porro reprehenderit tenetur quos quaerat pariatur accusamus ea veritatis ut! Sint rerum voluptate, nulla repellat voluptatem soluta quasi perspiciatis impedit adipisci, ducimus harum voluptas eos repellendus explicabo vel fugit mollitia error possimus odit quaerat, minus labore modi. Dicta facilis cum ea possimus id fuga natus eum nesciunt similique amet.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quisquam a corrupti, repellat quasi iure perferendis rerum officia quod necessitatibus at atque aut non reiciendis fuga doloribus sint iste voluptatem pariatur. Quo praesentium harum culpa, deleniti, eveniet temporibus veritatis sapiente distinctio, dignissimos mollitia tempore porro quos id voluptas ducimus. Nobis dicta dolores laboriosam architecto saepe! Velit hic a nisi odit, ea distinctio sequi eos. Vel, enim dolorum officiis odio eligendi in, ipsa iusto optio beatae architecto quas tempora laudantium quasi quisquam explicabo illum fugit laborum. Aperiam cum quisquam aut repudiandae libero soluta ab, doloribus laudantium, amet provident rem expedita nobis quidem?</div></div>
        <div className="video_link"><iframe className="iframe_vid" src={props.link4}></iframe><div className="information">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odit incidunt alias, ratione quibusdam asperiores illum explicabo expedita nulla itaque inventore iusto, voluptas fugiat quam perferendis consectetur nam maxime cumque, eius quisquam neque odio praesentium adipisci necessitatibus minima. Iusto quia, enim ex praesentium est pariatur. Culpa, officia! Quis suscipit fugit sint?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestiae, repudiandae eum quae soluta neque aspernatur natus aperiam similique, molestias at eius, dolores unde iusto reiciendis nulla error temporibus? Magnam totam sint iure ex et, necessitatibus id dolore non libero, doloremque aut iusto, corrupti tenetur modi molestias suscipit. Corrupti qui aliquid consequuntur facilis a omnis provident illo, rerum laborum architecto? Ducimus molestiae, fuga velit ipsum a voluptate quo, at id sapiente animi cumque provident nesciunt reprehenderit, alias praesentium nisi nam deleniti rem quae quod unde sed necessitatibus. Veniam debitis quidem illum incidunt maiores sequi qui sunt quaerat! Ratione animi explicabo et!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odit neque temporibus sapiente facilis placeat, fugiat nesciunt doloremque adipisci voluptate! Labore autem officiis maxime excepturi sunt distinctio veniam nemo ducimus, porro rem quae eligendi, id beatae libero praesentium enim nihil ea vitae. Et itaque dolores maiores, consequatur autem quia ullam velit tempora! Eius ullam provident cumque mollitia suscipit harum alias quibusdam ea ut placeat saepe a, molestias ex itaque ratione praesentium vero nulla commodi officia similique rerum, quam autem quae dolorem. Quae blanditiis facere ab nam culpa repudiandae hic officiis velit, alias modi odio, doloremque quam obcaecati minus placeat reprehenderit error?</div></div>

    </div>
    </div>
    </>
)
     
}

export default Bottom_Again;
